services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyMoney\:
        resource: '../../{Api,Repository,Service}'
        tags: ['controller.service_arguments']
