services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyMoney\:
        resource: '../../{Repository,Service}'

    Wexample\SymfonyMoney\Api\Controller\:
        resource: '../../Api/Controller/*'
        tags: ['controller.service_arguments']

    Wexample\SymfonyMoney\Api\Normalizer\:
        resource: '../../Api/Normalizer/*'
        tags: ['serializer.normalizer']
